query AllEpisodes($page: Int, $season: String) {
  episodes(page: $page, filter: { episode: $season }) {
    info {
      count
      pages
      next
    }
    results {
      id
      name
      episode
      characters {
        id
        name
      }
    }
  }
}
